### ISSUE TITLE
Error on non-English (German) Windows

### ISSUE THREAD

**Issue by trenki2** [vierofernando/python-weather#2]
Your Simple Usage example does not work as it is as await can only be used inside an async method!

I use the following code on a German Windows and get an error

```
import python_weather
import asyncio

async def main():
    client = python_weather.Client(format=python_weather.IMPERIAL)
    weather = await client.find("Washington DC")
    print(weather.current.temperature)
    for forecast in weather.forecast:
        print(str(forecast.date), forecast.sky_text, forecast.temperature)
    await client.close()

asyncio.run(main())
```

```
Traceback (most recent call last):
  File "c:\Users\markus\Downloads\test.py", line 12, in <module>
    asyncio.run(main())
  File "C:\Users\markus\AppData\Local\Programs\Python\Python37\lib\asyncio\runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "C:\Users\markus\AppData\Local\Programs\Python\Python37\lib\asyncio\base_events.py", line 587, in run_until_complete
    return future.result()
  File "c:\Users\markus\Downloads\test.py", line 6, in main
    weather = await client.find("Wien")
  File "C:\Users\markus\AppData\Local\Programs\Python\Python37\lib\site-packages\python_weather\client.py", line 83, in find
    return Weather(content)
  File "C:\Users\markus\AppData\Local\Programs\Python\Python37\lib\site-packages\python_weather\weather.py", line 53, in __init__
    self.current               = Forecast._current(data["current"])
  File "C:\Users\markus\AppData\Local\Programs\Python\Python37\lib\site-packages\python_weather\forecast.py", line 47, in _current
    _class.date              = datetime.strptime(f'{data["@date"]} {data["@observationtime"]}', "%Y-%d-%m %H:%M:%S")
  File "C:\Users\markus\AppData\Local\Programs\Python\Python37\lib\_strptime.py", line 577, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "C:\Users\markus\AppData\Local\Programs\Python\Python37\lib\_strptime.py", line 359, in _strptime
    (data_string, format))
ValueError: time data '2021-04-14 10:00:00' does not match format '%Y-%d-%m %H:%M:%S'
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001E699C74508>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x000001E699C87EB8>, 511227.875)]']
connector: <aiohttp.connector.TCPConnector object at 0x000001E699C74408>
```

The default date format for a German Windows is %Y-%m-%d and not %Y-%d-%m.
That is why your code breaks.

**Comment by vierofernando** [comment]
issue fixed on this pull request https://github.com/vierofernando/python-weather/pull/3
