### ISSUE TITLE
Api stopped working a few weeks ago

### ISSUE THREAD

**Issue by soyrandom1** [vierofernando/python-weather#6]
A few weeks ago i started having this error messages while trying to use the api. I did not change my code at all. 

`Traceback (most recent call last):
  File "C:\venv\lib\site-packages\python_weather\client.py", line 83, in find
    return Weather(content)
  File "C:\venv\lib\site-packages\python_weather\weather.py", line 53, in __init__
    self.current               = Forecast._current(data["current"])
  File "C:\venv\lib\site-packages\python_weather\forecast.py", line 47, in _current
    _class.date              = datetime.strptime(f'{data["@date"]} {data["@observationtime"]}', "%Y-%d-%m %H:%M:%S")
  File "C:\AppData\Local\Programs\Python\Python39\lib\_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "C:\AppData\Local\Programs\Python\Python39\lib\_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '2021-05-28 13:00:00' does not match format '%Y-%d-%m %H:%M:%S'
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000002881BCCF580>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x000002881BCCCB20>, 437676.25)]']
connector: <aiohttp.connector.TCPConnector object at 0x000002881BCCF550>
`

**Comment by vierofernando** [comment]
You are using an older version of `python-weather`. Try updating to the most recent version of it.
